[project]
name = "a2a-mcp"
version = "0.1.0"
description = "A2A - MCP Sample"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[sql]>=0.3.0,<0.4.0",
    "click>=8.1.8",
    "dynaconf>=3.3.5,<4",
    "fastmcp>=1.0",
    "google-adk>=1.0.0",
    "httpx>=0.28.1",
    "langchain-openai>=0.3.16",
    "langchain-mcp-adapters>=0.0.9",
    "langgraph>=1.2.11",
    "langgraph-cli[inmem]>=0.4.31",
    "mcp[cli]>=1.5.0",
    "nest-asyncio>=1.6.0",
    "networkx>=3.4.2",
    "numpy>=2.2.5",
    "openai>=1.78.1",
    "pandas>=2.2.3",
    "pydantic>=2.11.4",
    "litellm",
]

[dependency-groups]
dev = ["ipykernel>=6.29"]

[project.scripts]
a2a-mcp = "a2a_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
